CREATE TABLE IF NOT EXISTS links (
    id INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    link TEXT NOT NULL,
    fake_link TEXT NOT NULL UNIQUE,
    erase_time TIMESTAMP NOT NULL
);